language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 5.6
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
        - COVERAGE=true
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}
  - vendor/bin/phpspec run

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
