site_name: PortPHP Documentation
theme: readthedocs
pages:
- Introduction:
  - index.md
  - quickstart.md
- Components:
  - readers.md
  - writers.md
  - workflow.md
- About:
  - upgrading.md
  - contributing.md
site_url: http://portphp.org
repo_url: https://github.com/portphp/portphp
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - markdown_include.include:
      base_path: docs
